config/routes.rb
Rails.application.routes.draw do
 

  

  root 'pages#home'

  get  'about' => 'pages#about'

  get 'admin' => 'pages#admin'

  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'edit' => 'users#edit'


  get 'addbook' => 'books#new'

  
  resources :books
  resources :users

  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/pages/about.html.erb
<% provide(:title,"About  Us") %>

  
<h3>Why do we use it?</h3>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.<br> The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.<br> Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy.<br> Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

app/views/pages/contact.html.erb
<% provide(:title,"Contact Us") %>

   <h3>We love to hear from you, Contact US here:<br></h3>

<p>A-56, Sector – 64,<br>
  Nairobi-201301,<br>
  Uttar Route, Kenya.<br>
  Phone Number: xxx-xxx-xxx<br>
  Toll No 00-00-000-104 </p>
<h2 align="center">Customer Support</h2>
<form>
  <div class="row">
    <div class="medium-12 columns">
      <label>Name:<br>
        <input type="text" placeholder="Enter Your Name">

      </label><br>
      <label>Phone:<br>
        <input type="text" placeholder="Enter Phone Number">
        
      </label><br>
    
      <label>Email:<br>
        <input type="email" placeholder="Enter Your Email">
      </label>
      <label>Address:<br>
        <input type="text" placeholder="Enter Your Address">
      </label>
     <input type="submit" value="Submit" >
  </div>

</form>

app/views/pages/home.html.erb
<% provide(:title,"Home") %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<h1>Log in</h1>

		<%= form_for(:session, url: login_path) do |f| %>
		<%= f.label :email %>
		<%= f.email_field :email %>
		<%= f.label :password %>
		<%= link_to "(forgot password)", new_password_reset_path %>

		<%= f.password_field :password %>

		<%= f.label :remember_me, class: "checkbox inline" do %>
		<%= f.check_box :remember_me %>
		<span>Remember me on this computer</span>
		<% end %>

		<%= f.submit "Log in" %>
		<% end %>
	<p>New user? <%= link_to "Sign up now!", signup_path %></p>
</div>