config/routes.rb
Rails.application.routes.draw do
 

  

  root 'pages#home'

  get  'about' => 'pages#about'

  get 'admin' => 'pages#admin'

  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'edit' => 'users#edit'


  get 'addbook' => 'books#new'

  
  resources :books
  resources :users

  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :admin_user, only: [:edit,:create, :update, :destroy] 
  before_action :logged_in_user, only: [:index,:show]


  def index

    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] ="Book added successfully!" 
      redirect_to @book
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:success] = "Book updated"
      redirect_to @book
    else
      render 'edit'
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "please login"
      redirect_to login_url
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:succes] = "Book deleted!"
    redirect_to books_url

  end

  private

  def book_params
    params.require(:book).permit(:book_title, :category, :author, :isbn, :status)
  end
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "please log in."
      redirect_to login_url
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% provide(:title, 'Edit Book') %>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h3>Edit Book</h3>
        <%= form_for(@book) do |f| %>
            <%= render 'shared/errors_book' %>
            <%= f.label :book_title %>
            <%= f.text_field :book_title, class: 'form-control' %>
            <%= f.label :author %>
            <%= f.text_field :author, class: 'form-control' %>
            <%= f.label :category %>
            <%= f.text_field :category, class: 'form-control' %>
            <%= f.label :isbn %>
            <%= f.text_field :isbn, class: 'form-control' %>
            <%= f.label :status %>
            <%= f.text_field :status, class: 'form-control' %>
            <%= f.submit "Save Changes" %>
        <% end %>
    </div>
</div>

app/views/books/index.html.erb
<% provide(:title, 'All books') %>
<% if current_user.admin?%>
<%= link_to  "Add Book", addbook_path %>
<% end %>

<h2>All Books</h2>
<ul class="users">

    <% @books.each do |book| %>
        <li>
            <%= link_to book.book_title, book %>
            <% if current_user.admin? %>
                |<%= link_to "Edit",edit_book_path(book) %>
            | <%= link_to "Delete", book, method: :delete, data: {confirm: "Are you sure you want to delete this book??"} %>
    <% end %>
        </li>
    <% end %>
</ul>

app/views/books/new.html.erb
<% provide(:title, 'Add Book') %>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<h3>Add Book</h3>
<%= form_for(@book) do |f| %>
<%= render 'shared/errors_book' %>
<%= f.label :book_title %>
<%= f.text_field :book_title, class: 'form-control' %>
<%= f.label :author %>
<%= f.text_field :author, class: 'form-control' %>
<%= f.label :category %>
<%= f.text_field :category, class: 'form-control' %>
<%= f.label :isbn %>
<%= f.text_field :isbn, class: 'form-control' %>
<%= f.label :status %>
<%= f.text_field :status, class: 'form-control' %>
<%= f.submit "Submit" %>
<% end %>
</div>
</div>

app/views/books/show.html.erb
<%= link_to  "Add Book", addbook_path %>

<table>

    <tr>
        <th>Book Title</th>
        <td><%= @book.book_title %></td>
        
    </tr>

      <tr>
        <th>Category</th>
        <td><%= @book.category %></td>
        

       </tr>
       <tr>
       <th>Author</th>
       <td><%= @book.author %></td>
        
        


       </tr>
       <tr>
        <th>ISBN</th>
        <td><%= @book.isbn %></td>
        

        </tr>
        <tr>
        <th>Status</th>
        <td><%= @book.status %></td>
        
        </tr>
    </tr>
</table>
 