config/routes.rb
Rails.application.routes.draw do
 

  

  root 'pages#home'

  get  'about' => 'pages#about'

  get 'admin' => 'pages#admin'

  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  get 'edit' => 'users#edit'


  get 'addbook' => 'books#new'

  
  resources :books
  resources :users

  resources :account_activation, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.erb
<header>
  
  
  
  

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Library App</li>
      <li><%= link_to "Home", root_path %></li>
     <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
         <li><%= link_to "books", books_path %></li>
     <li><%= link_to "Profile", current_user %></li>
     <li><%= link_to "Settings", edit_user_path(current_user) %></li>
     <li><%= link_to "Log out", logout_path, method: "delete" %></li>
     <% else %>
     <li><%= link_to "Log in", login_path %></li>
     <% end %>
    </ul>
  </div>
 
</div> 	
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Library System" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

<% flash.each do |message_type, message| %>
<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

    <%= yield %>

  </body>
</html>